site_name: LiveLife
site_url: https://cherui-yang.github.io/public-blog/

theme:
  name: material
  features:
    - navigation.instant   # 这一行必须有

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html   # 这个扩展可以防止 HTML 块干扰公式

extra_javascript:
  - javascripts/mathjax.js                 # 我们刚创建的文件
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # 引入MathJax库

extra_css:
  - stylesheets/extra.css

plugins:
  - search
plugins:
  - search
  - copy_md:
      source_dir: docs/geogebra
      target_dir: geogebra
      extensions: ['.html']   # 只复制 .html 文件（如果需要 .md 可加 '.md'）
extra_files:
  - docs/geogebra/1.1.html
  - docs/geogebra/1.2.html