site_name: 广油生存指南
site_url: https://cherui-yang.github.io/public-blog/

theme:
  name: material
  features:
    - navigation.instant   # 这一行必须有

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html   # 这个扩展可以防止 HTML 块干扰公式

extra_javascript:
  - javascripts/mathjax.js                 # 我们刚创建的文件
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # 引入MathJax库

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - copy_md:
      source_dir: docs/geogebra
      target_dir: geogebra
      # 你可以根据需要调整文件类型匹配规则
      # 如果希望复制所有 .html 文件，可以不加 extensions 参数